# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e96c1805cc36f26c9288f68b46e5e5db5bdb6eda8e81530046987ed6671c1f601e9f94aa22e5f7d37aae521a752367c6a1f36e44f3bc366844444608fc207ea9

test:
  secret_key_base: 82a74699632003298a7f0b2d30a708a74017a667fbf29e374b35bc4e751f84f74afa0cef898f8499a302417b2ae44da11e4708378037195c81b95f28ea671ea5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
